import type { CircleSpotlight, DropIn, MapAvatar, MonetizationTier, PresenceSpot, RealmDefinition, SafetyPillar, StoryCard } from './types';

export const REALMS: RealmDefinition[] = [
  {
    id: 'professional',
    title: 'Professional Realm',
    description: 'Portfolio-ready energy, curated to build business, mentorship, and premium collaborations.',
    accent: '#6BA4FF',
    aura: 'from-blue-500/80 via-blue-400/40 to-transparent',
    mapTheme: 'bg-gradient-to-br from-slate-900 via-blue-950 to-black',
    icon: 'Briefcase',
  },
  {
    id: 'social',
    title: 'Social Realm',
    description: 'Effortless hangs, lifestyle vibes, creative collectives, and friends-of-friends.',
    accent: '#27E1C1',
    aura: 'from-emerald-400/80 via-teal-400/40 to-transparent',
    mapTheme: 'bg-gradient-to-br from-slate-900 via-emerald-950 to-black',
    icon: 'Users',
  },
  {
    id: 'dating',
    title: 'Dating Realm',
    description: 'Intentional chemistry, compatibility insights, and genuine romance energy.',
    accent: '#FF6B9A',
    aura: 'from-pink-500/80 via-rose-400/40 to-transparent',
    mapTheme: 'bg-gradient-to-br from-slate-900 via-rose-950 to-black',
    icon: 'Heart',
  },
  {
    id: 'sexual',
    title: 'Sexual Realm',
    description: 'Adult-only desire with consent-first guardrails and visibility gating.',
    accent: '#E33E3E',
    aura: 'from-red-500/80 via-red-400/40 to-transparent',
    mapTheme: 'bg-gradient-to-br from-slate-900 via-red-950 to-black',
    icon: 'Flame',
  },
  {
    id: 'neutral',
    title: 'Neutral Realm',
    description: 'Soft landing space while calibrating your vibe or choosing a direction.',
    accent: '#94A3B8',
    aura: 'from-slate-400/80 via-slate-300/30 to-transparent',
    mapTheme: 'bg-gradient-to-br from-slate-900 via-slate-800 to-black',
    icon: 'Sparkles',
  },
];

export const PRESENCE_SPOTS: PresenceSpot[] = [
  {
    id: 'soma-studio',
    label: 'SOMA Studio Loft',
    realm: 'professional',
    auraIntensity: 0.8,
    compatibility: 92,
    vibe: 'Pitch-perfect decks, creative strategy sprint.',
    intent: 'Collab ready',
  },
  {
    id: 'mission-rooftop',
    label: 'Mission Rooftop',
    realm: 'social',
    auraIntensity: 0.6,
    compatibility: 81,
    vibe: 'Sunset tonic club & vinyl swap.',
    intent: 'Meet curated friends',
  },
  {
    id: 'dolores',
    label: 'Dolores South Field',
    realm: 'dating',
    auraIntensity: 0.7,
    compatibility: 78,
    vibe: 'Picnic invites + poetry drop-ins.',
    intent: 'Flirt & see chemistry',
  },
  {
    id: 'afterhours',
    label: 'Private Afterhours',
    realm: 'sexual',
    auraIntensity: 0.9,
    compatibility: 85,
    vibe: 'Invite-only red light lounge.',
    intent: 'Consent-first play',
  },
  {
    id: 'atrium',
    label: 'Transcentral Atrium',
    realm: 'neutral',
    auraIntensity: 0.5,
    compatibility: 74,
    vibe: 'Gallery walkthrough & decompress.',
    intent: 'Reset & observe',
  },
];

export const MAP_AVATARS: MapAvatar[] = [
  {
    id: 'leo-bitmoji',
    name: 'Leo',
    realm: 'social',
    intent: 'Kiki host',
    mood: 'Neon nights',
    x: 22,
    y: 34,
    accent: '#27E1C1',
  },
  {
    id: 'amir-pro',
    name: 'Amir',
    realm: 'professional',
    intent: 'Deck doctor',
    mood: 'Crisp & direct',
    x: 58,
    y: 28,
    accent: '#6BA4FF',
  },
  {
    id: 'noah-date',
    name: 'Noah',
    realm: 'dating',
    intent: 'Slow brunch',
    mood: 'Soft sunlight',
    x: 38,
    y: 62,
    accent: '#FF6B9A',
  },
  {
    id: 'ruby-sensual',
    name: 'Ruby',
    realm: 'sexual',
    intent: 'Invite-only',
    mood: 'Velvet hush',
    x: 71,
    y: 64,
    accent: '#E33E3E',
  },
  {
    id: 'skye-neutral',
    name: 'Skye',
    realm: 'neutral',
    intent: 'Observing',
    mood: 'Resetting',
    x: 14,
    y: 70,
    accent: '#94A3B8',
  },
  {
    id: 'parker-social',
    name: 'Parker',
    realm: 'social',
    intent: 'Gallery crawl',
    mood: 'Chill glam',
    x: 78,
    y: 40,
    accent: '#27E1C1',
  },
  {
    id: 'elliot-pro',
    name: 'Elliot',
    realm: 'professional',
    intent: 'Mentor hour',
    mood: 'Black turtleneck',
    x: 48,
    y: 14,
    accent: '#6BA4FF',
  },
];

export const DROP_INS: DropIn[] = [
  {
    id: 'dropin-1',
    title: 'Cinematic moodboard review',
    realm: 'professional',
    expiresInMinutes: 45,
    content: 'Need motion designer to finesse a 15s reel. Credits + $$',
    coordinates: 'Pier 70',
  },
  {
    id: 'dropin-2',
    title: 'Aura club + ballroom warmup',
    realm: 'social',
    expiresInMinutes: 30,
    content: 'Bring metallic, leave ego.',
    coordinates: 'SoMa safe space',
  },
  {
    id: 'dropin-3',
    title: 'GhostChat unlocked: rooftop rosé',
    realm: 'dating',
    expiresInMinutes: 90,
    content: 'Mutual opt-in to unlock coordinates.',
    coordinates: 'Mission private pin',
  },
];

export const STORIES: StoryCard[] = [
  {
    id: 'story-1',
    author: 'Kenji · Industrial Designer',
    realm: 'professional',
    headline: 'Signed 2 contracts from SceneHim intros.',
    duration: '16h left',
    cover: '/stories/pro.jpg',
  },
  {
    id: 'story-2',
    author: 'Diego · Culture Curator',
    realm: 'social',
    headline: 'Hosting 20 new creatives tonight.',
    duration: '5h left',
    cover: '/stories/social.jpg',
  },
  {
    id: 'story-3',
    author: 'Nico · Set Designer',
    realm: 'dating',
    headline: 'Mutual playlists unlocked 🔐',
    duration: '23h left',
    cover: '/stories/dating.jpg',
  },
];

export const CIRCLES_AND_EVENTS: CircleSpotlight[] = [
  {
    id: 'circle-1',
    name: 'Off-the-record Strategy Circle',
    realm: 'professional',
    location: 'Founders Club · SF',
    members: 32,
    type: 'circle',
    status: 'curated',
  },
  {
    id: 'circle-2',
    name: 'Night Bloom Supper',
    realm: 'social',
    location: 'Secret Garden · Oakland',
    members: 18,
    type: 'event',
    status: 'open',
  },
  {
    id: 'circle-3',
    name: 'Consent Couture',
    realm: 'sexual',
    location: 'Private loft · SOMA',
    members: 40,
    type: 'event',
    status: 'curated',
  },
];

export const SAFETY_PILLARS: SafetyPillar[] = [
  {
    id: 'safety-1',
    title: 'Multi-layer privacy',
    description: 'Location jitter, blurred avatars in sexual realm, encrypted GhostChat.',
    badges: ['Location Jitter', 'Age Gate', 'Screenshot traps'],
  },
  {
    id: 'safety-2',
    title: 'Community guardians',
    description: 'Resident moderators per realm + 24/7 escalation bridge.',
    badges: ['On-call hosts', 'Report SLA < 5m', 'Real human review'],
  },
  {
    id: 'safety-3',
    title: 'Consent-intel',
    description: 'Mutual opt-in messaging, verification layers, language filters.',
    badges: ['Realm locking', 'Behavior score', 'Crisis mode'],
  },
];

export const MONETIZATION: MonetizationTier[] = [
  {
    id: 'free',
    title: 'Essentials',
    description: 'Baseline access to Realms, atmospheric map, and drop-ins.',
    price: '$0',
    benefits: ['2 boosts / month', 'GhostChat in neutral & social', 'Map auras basic'],
  },
  {
    id: 'pro',
    title: 'SceneHim Pro',
    description: 'Priority placement, AI avatar wardrobe packs, pro analytics.',
    price: '$24 / mo',
    benefits: ['Unlimited boosts', 'Realm scheduling', 'Audience insights', 'Event RSVPs priority'],
  },
  {
    id: 'brands',
    title: 'Brand Galleries',
    description: 'Premium spaces for labels, nightlife groups, and queer collectives.',
    price: 'Custom',
    benefits: ['Promoted events', 'Scene commerce', 'Cinematic microsites'],
  },
];
